---
repository:
  name: github_exporter
  description: Prometheus exporter for GitHub
  homepage: https://promhippie.github.io/github_exporter/
  topics: prometheus, prometheus-exporter, metrics, github

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  allow_update_branch: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - testing
      enforce_admins: false
      restrictions:
        apps:
          - renovate
          - promhippie
        users: []
        teams:
          - admins
          - bots
          - members

...
