---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: changes

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  envvars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        if: github.event_name != 'pull_request'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: PR checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup golang
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod

      - name: Setup task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate envvars
        run: task envvars

      - name: Commit changes
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: docs/partials/envvars.md
          message: "docs: automated envvars update"
          push: true
          commit: --signoff

  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        if: github.event_name != 'pull_request'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: PR checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup golang
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod

      - name: Setup task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metrics
        run: task metrics

      - name: Commit changes
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: docs/partials/metrics.md
          message: "docs: automated metrics update"
          push: true
          commit: --signoff

  labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        if: github.event_name != 'pull_request'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: PR checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup golang
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod

      - name: Setup task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate labels
        run: task labels

      - name: Commit changes
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: docs/partials/labels.md
          message: "docs: automated labels update"
          push: true
          commit: --signoff

...
