---
name: docker

"on":
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - platform: linux/386
            goos: linux
            goarch: 386
          - platform: linux/amd64
            goos: linux
            goarch: amd64
          - platform: linux/arm64
            goos: linux
            goarch: arm64
          - platform: linux/arm/6
            goos: linux
            goarch: arm
            goarm: 6

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Run generate
        id: generate
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: make generate

      - name: Run build
        id: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: make build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            promhippie/github-exporter
            quay.io/promhippie/github-exporter
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/promhippie/github_exporter/master/README.md
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Hub login
        id: login1
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build image
        id: publish
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile.${{ matrix.goos }}.${{ matrix.goarch }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

  manifest:
    runs-on: ubuntu-20.04
    needs: docker

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Hub tags
        id: hubTags
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: promhippie/github-exporter
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Hub manifest
        id: hub
        uses: actionhippie/manifest@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6
          template: promhippie/github-exporter:VERSION-OS-ARCH
          target: ${{ steps.hubTags.outputs.tags }}
          ignore_missing: true

      - name: Quay tags
        id: quayTags
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: quay.io/promhippie/github-exporter
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Quay manifest
        id: quay
        uses: actionhippie/manifest@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6
          template: quay.io/promhippie/github-exporter:VERSION-OS-ARCH
          target: ${{ steps.quayTags.outputs.tags }}
          ignore_missing: true

  readme:
    runs-on: ubuntu-20.04
    needs: docker

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Hub readme
        id: hub
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          target: promhippie/github-exporter
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Prometheus exporter for GitHub
          readme: README.md

      - name: Quay readme
        id: quay
        uses: actionhippie/pushrm@v1
        with:
          provider: quay
          target: quay.io/promhippie/github-exporter
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
